stages:
  - build

gcc-4:
  stage: build
  image: gcc:4
  tags:
    - docker

gcc-5:
  stage: build
  image: gcc:5
  tags:
    - docker

script:
  - apt update && apt install -y cmake python-pip
  - pip install conan
  - conan user
  - conan test_package --build=missing