before_script:
  - apt update && apt install g++-6 cmake python-pip
  - pip install conan
  - conan user

stages:
  - build
  - test

gcc-6:
  stage: build
  script:
    - conan test_package --build=missing
  tags:
    - docker
