before_script:
  - apt update && apt install -y cmake python-pip python-dev
  - pip install conan
  - conan user
  - conan remote add cpp-russia-ci http://cpp-russia-ci3.filonovpv.name:9300

stages:
  - build
  - deploy

build:gcc-4:
  stage: build
  image: gcc:4
  script:
    - conan test_package --build=missing
  tags:
    - docker
  artifacts:
    paths:
      - /root/.conan/*

# build:gcc-5:
#   stage: build
#   image: gcc:5
#   script:
#     - conan test_package --build=missing
#   tags:
#     - docker

# build:gcc-6:
#   stage: build
#   image: gcc:6
#   script:
#     - conan test_package --build=missing
#   tags:
#     - docker

# build:clang-3.9:
#   stage: build
#   image: walberla/buildenv-ubuntu-clang:3.9
#   script:
#     - conan test_package --build=missing
#   tags:
#     - docker

deploy:gcc-4:
  stage: deploy
  only:
    - feature/2-upload-packages-to-conan
    - master
  tags:
    - docker
  script:
    - conan upload -r cpp-russia-ci "hello/*" --all
  dependencies:
    - build:gcc-4

# apple-clang-8.0:
#   stage: build
#   script:
#     - conan test_package --build=missing
#   tags:
#     - osx
