dist: trusty
language: cpp

install:
  - ./.travis/install.sh

script:
  - ./.travis/activate.sh
  - mkdir build && cd build
  - conan install .. -s build_type=$BUILD_TYPE --build=missing
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$COMPILER
  - cmake --build . -- VERBOSE=1
  - ctest -V


env:
  - BUILD_TYPE=Release C_COMPILER=gcc-4.9 CXX_COMPILER=g++-4.9
  - BUILD_TYPE=Release C_COMPILER=gcc-5 CXX_COMPILER=g++-5
  - BUILD_TYPE=Release C_COMPILER=gcc-6 CXX_COMPILER=g++-6
  - BUILD_TYPE=Release C_COMPILER=gcc-3.9 CXX_COMPILER=clang++-3.9
  - BUILD_TYPE=Release C_COMPILER=gcc-4.0 CXX_COMPILER=clang++-4.0
  - BUILD_TYPE=Debug C_COMPILER=gcc-4.9 CXX_COMPILER=g++-4.9
  - BUILD_TYPE=Debug C_COMPILER=gcc-5 CXX_COMPILER=g++-5
  - BUILD_TYPE=Debug C_COMPILER=gcc-6 CXX_COMPILER=g++-6
  - BUILD_TYPE=Debug C_COMPILER=gcc-3.9 CXX_COMPILER=clang++-3.9
  - BUILD_TYPE=Debug C_COMPILER=gcc-4.0 CXX_COMPILER=clang++-4.0


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-3.9
      - llvm-toolchain-trusty-4.0
    packages:
      - g++-4.9
      - g++-5
      - g++-6
      - clang-3.9
      - clang-4.0

matrix:
  include:
    - os: osx
      osx_image: xcode6.4
      env: BUILD_TYPE=Debug
    - os: osx
      osx_image: xcode7.3
      env: BUILD_TYPE=Debug
    - os: osx
      osx_image: xcode8
      env: BUILD_TYPE=Debug
    - os: osx
      osx_image: xcode8.2
      env: BUILD_TYPE=Debug
    - os: osx
      osx_image: xcode6.4
      env: BUILD_TYPE=Release
    - os: osx
      osx_image: xcode7.3
      env: BUILD_TYPE=Release
    - os: osx
      osx_image: xcode8
      env: BUILD_TYPE=Release
    - os: osx
      osx_image: xcode8.2
      env: BUILD_TYPE=Release


